### ISSUE TITLE
Support `config.extends` for `.markdownlint-cli2.jsonc` config file

### ISSUE THREAD

**Issue by Divlo** [DavidAnson/markdownlint-cli2#108]
Hello! :wave:

Since `markdownlint-cli2` v0.6.0 has been released with `markdownlint` v0.27.0 including `markdownlint/style/prettier`, I wanted to use it.
However it seems like that using the `.markdownlint-cli2.jsonc` config, `config.extends` property is not working:
```jsonc
{
  "config": {
    "default": true,
    "extends": "./node_modules/markdownlint/style/prettier.json"
  },
  "globs": ["**/*.{md,mdx}"],
  "ignores": ["**/node_modules"]
}
```

While using `.markdownlint.json`, it worked:
```json
{
  "default": true,
  "extends": "./node_modules/markdownlint/style/prettier.json"
}
```

I'd rather continue using `.markdownlint-cli2.jsonc`, as I like the idea of having config file instead of passing configs with CLI arguments, notably for loading `customRules`, it is also easier with the VSCode extension, so both the CLI and the IDE configs are in sync "automatically".

I consider this as a bug, am I correct, that it isn't the expected behavior?
That the `config` property in `.markdownlint-cli2.jsonc` should resolve the same way as `.markdownlint.json`.

**Comment by DavidAnson** [comment]
I'm not sure if I want to support this or not, so I will leave this open to think about. However, I think you can get the behavior you want today by using both files. Leave the configuration in `.markdownlint.json` like you originally had it and remove the "config" section from `.markdownlint-cli2.jsonc`. As I recall, the two files will be merged.

**Comment by Divlo** [comment]
Ah, I didn't know `.markdownlint.json` and `.markdownlint-cli2.jsonc` would be merged, it indeed works, thanks!

I find it odd to have 2 configs file for markdown linting, we already have so many configs files, so when we can, it might be better to avoid. I can live with it, but having the `"config"` property with same behavior as `.markdownlint.json` would be a better DX.

> I'm not sure if I want to support this or not, so I will leave this open to think about.

Alright, sounds good! :+1:

**Comment by mi-hol** [comment]
> I find it odd to have 2 configs file for markdown linting, we already have so many configs files

I'm sharing the same view . Was a decision perhaps made already?

**Comment by DavidAnson** [comment]
I replied above. Nothing new since then. I'll revisit this on the next round of changes.

**Comment by FISHMANPET** [comment]
FWIW, I'm happy with the current behavior, where multiple config files can co-exist and are eventually merged.  I'm storing my configuration around rules in a .markdownlint.yml file, and then in my pipeline I'm actually generating a very barebones .markdownlint-cli2.jsonc file that just enables the junit formatter and sets the file name.

This is being used in multiple projects that share a CI/CD pipeline definition.  Essentially it lets the repo users define what markdownlint rules they want in their own repo, but then I get to control the output formatter that's ultimately used within the pipeline, completely transparently from the document writer.

**Comment by DavidAnson** [comment]
@Divlo, note the cleaner way of referencing the suggested `prettier` style since it's exported by `markdownlint` and packages are resolved by `extends`:
https://github.com/DavidAnson/markdownlint-cli2/blob/ddd2d602ff2f2dd9b0ec005955b43c2b59ac74ff/test/markdownlint-cli2-extends/package/.markdownlint-cli2.jsonc#L3
