### ISSUE TITLE
markdownlint-cli2 error on travis

### ISSUE THREAD

**Issue by rshade** [DavidAnson/markdownlint-cli2#11]
I am getting an error when I try to run markdownlint-cli2 on travis, any ideas where to look?: 
./node_modules/.bin/markdownlint-cli2 "**/*.md" "#node_modules"
/home/travis/build/$project/node_modules/markdownlint-cli2/markdownlint-cli2.js:216
  for await (const file of globby.stream(globPatterns)) {
      ^^^^^
SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by DavidAnson** [comment]
"globby" is not a reserved word, but it's near "await" which is not supported by older versions of Node. CLI2 declares support for Node 10+ - please check what Node version Travis is using.

**Comment by rshade** [comment]
@DavidAnson thank you. I am doing the following:
`- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
- sudo apt-get install nodejs -y
- curl -L https://www.npmjs.com/install.sh | sh
- npm install
`
with script:
`
script:
- bundle exec danger --verbose
- ./node_modules/.bin/markdownlint-cli2 "**/*.md" "#node_modules"
`

**Comment by DavidAnson** [comment]
Can you show the output of `node --version`?

**Comment by DavidAnson** [comment]
Also, have you seen this guidance: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by rshade** [comment]
@DavidAnson that was definitely it. It's 8.x by default, I set a variable and did this: 
```
- echo $NVM_DIR;
- nvm --version;
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- node -v
```
any idea why it might ignore my .markdownlint.json in ci, whereas it obeys it locally, any way I can pass it a -c .markdownlint.json
