### ISSUE TITLE
`fix` option not applied in config file used with `markdownlint-cli2-config`

### ISSUE THREAD

**Issue by RezaRahemtola** [DavidAnson/markdownlint-cli2#110]
Hello,

I just started implementing `mardownlint-cli2` and noticed a weird case.

I have this simple config in `config/.markdownlint-cli2.jsonc`:
```json
{
  "config": {
    "line-length": false
  },
  "fix": true
}
```

When running `markdownlint-cli2-config "config/.markdownlint-cli2.jsonc" "**/*.md"` at the root of my project, I expect:
- The `line-length` rule to be disabled in the entire project (works)
- Markdown files with other errors fixed in the entire project (doesn't work)

Duplicating one of my file to the `config` folder and running the command again (or even just `markdownlint-cli2`) will fix it.

As [your README](https://github.com/DavidAnson/markdownlint-cli2#command-line) states that with `markdownlint-cli2`:
> The specified configuration file will be loaded, parsed, and applied as a base configuration for the current directory - which will then be handled normally.

then I don't think that it's an expected behavior, and if it is how can I use the CLI to fix errors with a configuration file stored in a different folder?

Thanks,

**Comment by SichangHe** [comment]
So, will having a `"fix": true` be the only way to fix files while using a config file?
That would mean that I have to duplicate my `.markdownlint-cli2.jsonc` and make a copy with `"fix": true`.
Can we have a `markdownlint-cli2-config-fix` or something equivalent?

**Comment by SichangHe** [comment]
Could you explain how this is considered fixed, @DavidAnson, please?

**Comment by SichangHe** [comment]
Then, I could work around it. Thanks.

Also, I had to force NPM to update:

```shell
npm i -g markdownlint-cli2 -f
```
