### ISSUE TITLE
GitHub Actions annotations

### ISSUE THREAD

**Issue by szepeviktor** [DavidAnson/markdownlint-cli2#111]
Hello! 👋🏻 

Are there plans to add a GHA [annotations](https://github.blog/2018-12-14-introducing-check-runs-and-annotations/) formatter?

**Comment by DavidAnson** [comment]
Annotations are already supported by the GitHub Action: https://github.com/marketplace/actions/markdownlint-cli2-action

**Comment by szepeviktor** [comment]
Thank you!
