### ISSUE TITLE
Docker access to volume running markdownlint-cli2-fix

### ISSUE THREAD

**Issue by kkaiser** [DavidAnson/markdownlint-cli2#113]
Dear all,

thanks for this great project. When running the [fix command in docker](https://github.com/DavidAnson/markdownlint-cli2#container-image) I get a permission denied error when the cli tool is trying to auto fix the issue.

```bash
docker run -v $PWD:/workdir --entrypoint="markdownlint-cli2-fix" davidanson/markdownlint-cli2:v0.6.0 "**/*.md" "#node_modules"
```

```text
Unable to find image 'davidanson/markdownlint-cli2:v0.6.0' locally
v0.6.0: Pulling from davidanson/markdownlint-cli2
c158987b0551: Already exists 
aabd449b9131: Pull complete 
756e97429a30: Pull complete 
1ee3f64a4fc8: Pull complete 
78ef5a8c8e64: Pull complete 
36750bd49a9e: Pull complete 
4b29cbb623cd: Pull complete 
60e807a0657a: Pull complete 
Digest: sha256:3a85e5f36f3f6af2b01f9b295b10aecc07df72ba18fab51cfc8caedffe495240
Status: Downloaded newer image for davidanson/markdownlint-cli2:v0.6.0
markdownlint-cli2-fix v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md !node_modules
Linting: 62 file(s)
[Error: EACCES: permission denied, open '/workdir/projects/test.md'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/workdir/projects/test.md'
}
```

If this is a Docker issue what options would you suggest to mitigate this.

**Comment by DavidAnson** [comment]
I think that error is saying the account running the process does not have write (or perhaps any) access to that file which has been mapped into the image's working directory. If the same command works without passing "-fix", that would confirm it is a write permission issue. If it fails even for read, I can double-check on my side, but I haven't heard from anyone else about this being an issue.

**Comment by kkaiser** [comment]
Thanks for the quick reply! 

You are right, I didn't think of this simple thing. Since the container runs as root it also needs to be writable for others. I think this might also happen because I run [rootless docker](https://docs.docker.com/engine/security/rootless/). Adding write for others works

```bash
find ./ -type f -iname "*.md" -exec chmod o+w {} \;
```
