### ISSUE TITLE
Can I lint and fix without having two nearly identical config files?

### ISSUE THREAD

**Issue by KillyMXI** [DavidAnson/markdownlint-cli2#12]
Can I lint and fix without having two nearly identical config files?

With `markdownlint-cli` I can have only the rules file and call it from npm scripts the way I want it.
The only things I needed were the ignore pattern and the "fix" flag.
I could probably live with `markdownlint-cli2.jsonc` for common arguments such as ignore pattern.
But having a separate config for a mere "fix" flag - I find unacceptable.

I've chosen `markdownlint-cli` some time ago for this reason. I'm now reconsidering my options for a completely different reason, so I decided to bring this issue here.

**Comment by DavidAnson** [comment]
Thinking out loud: Would allowing config files to reference environment variables work for your scenario?

**Comment by KillyMXI** [comment]
Sounds like a needless complication, a wrong tool for the task.
I also suspect it may create issues on different platforms. (It must work on Windows and *nix without extra effort.)

**Comment by DavidAnson** [comment]
Another approach is to export a `markdownlint-cli2-fix` command which behaves exactly the same, but defaults `fix` to `true` at the root level (it could still be overridden).

**Comment by KillyMXI** [comment]
Well, that's something. Pretty straightforward and should work everywhere.

**Comment by DavidAnson** [comment]
I have it mapped out in my head and will try it soon.
