### ISSUE TITLE
Default ignores?

### ISSUE THREAD

**Issue by KillyMXI** [DavidAnson/markdownlint-cli2#13]
I would like to automatically ignore paths based on `.gitignore`.

This way I don't have to maintain a separate ignore list and save myself from possible issues when two lists get out of sync.

It is currently solvable in `markdownlint-cli` with `--ignore-path` but I can't see a way to achieve this with `markdownlint-cli2`.

**Comment by DavidAnson** [comment]
Please see https://github.com/DavidAnson/markdownlint-cli2/issues/1 for a discussion of this topic.

**Comment by KillyMXI** [comment]
Oh, ok.
