### ISSUE TITLE
How do I use custom rules?

### ISSUE THREAD

**Issue by iainelder** [DavidAnson/markdownlint-cli2#130]
I want to use [markdownlint-rule-github-internal-links](https://github.com/edemaine/markdownlint-rule-github-internal-links).

Its documentation says to use it all I have to do is add the following to my config. It shows a JSON example. I use YAML, so:

```yaml
customRules:
  - "markdownlint-rule-github-internal-links"
```

I've installed markdownlint-cli2 globally in npm.

So I run it like this:

```bash
markdownlint-cli2 **.md
```

On a document that contains a definitely-broken link like this:

```markdown
[Broken](broken.md)
```

And I get the following:

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **.md
Linting: 4 file(s)
Summary: 0 error(s)
```

It looks like markdownlint-cli2 is ignoring my extra config.

If I type nonsense in the list of customRules it makes no difference.

How do I actually use a custom rule?

I read the [Custom Rules](https://github.com/DavidAnson/markdownlint/blob/main/doc/CustomRules.md) documentation. It might be useful for rule developers, but it doesn't show how to use a rule.

I tried installing the rule globally as suggested in #24:

```bash
 npm install -g markdownlint-rule-github-internal-links
```

The output was the same: 0 errors.

**Comment by DavidAnson** [comment]
> If I type nonsense in the list of customRules it makes no difference.

This sentence strongly suggests that your configuration file is not being used. Invalid YAML or a nonexistent custom rule should both cause the CLI to fail with an error message.

The name of that file needs to be one of the supported ones and it should generally be in the root of your project where you invoke the CLI from. Please double check that.

The documentation includes YAML examples here: https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2yaml

**Comment by iainelder** [comment]
@DavidAnson, thanks for the feedback. I'll check it and get back to you.

**Comment by iainelder** [comment]
Here's a repro for what I'm seeing. Am I doing something wrong?

I already have markdownlint-cli2 installed globally.

```console
$ markdownlint-cli2 | head -1
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
```

I make a new empty directory.

```
cd "$(mktemp --dir)"
```

I create a markdownlint config with a basic setting just to have something there.

```console
$ markdownlint-cli2 | head -1
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
```

I make a new empty directory.

```
cd "$(mktemp --dir)"
```

I create a markdownlint config with a basic setting just to have something there.


```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false
EOF
```

I write a test file that should trigger the single-h1 rule.

```bash
cat > bad-doc.md <<"EOF"
# Heading

# Dupe
EOF

I run markdownlint-cli2.

```bash
markdownlint-cli2 "**/*.md"
```

It detects the file and detects the formatting error.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
Summary: 1 error(s)
bad-doc.md:3 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Dupe"]
```

I change the config to add a custom rule with a nonsense name.

```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false

customRules:
  - "not-a-real-rule"
EOF
```

I run markdownlint-cli2 again. It seems to ingore the changes to the config. The output is the same.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
Summary: 1 error(s)
bad-doc.md:3 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Dupe"]
```

I change the config once more to add some invalid syntax.

```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false

customRules:
  - "not-a-real-rule"

invalid_syntax
EOF
```

I run markdownlint-cli2 again. This time it fails because of the syntax error.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Error: Unable to parse '/home/isme/tmp/tmp.2023-03-02.g1d5paLo/.markdownlint.yaml'; Parser 0: Unexpected number in JSON at position 1; Parser 1: Implicit map keys need to be followed by map values at line 7, column 1:


invalid_syntax
^^^^^^^^^^^^^^

    at /home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/node_modules/markdownlint/lib/markdownlint.js:1098:23

```

```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false
EOF
```

I write a test file that should trigger the single-h1 rule.

```bash
cat > bad-doc.md <<"EOF"
# Heading

# Dupe
EOF

I run markdownlint-cli2.

```bash
markdownlint-cli2 "**/*.md"
```

It detects the file and detects the formatting error.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
Summary: 1 error(s)
bad-doc.md:3 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Dupe"]
```

I change the config to add a custom rule with a nonsense name.

```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false

customRules:
  - "not-a-real-rule"
EOF
```

I run markdownlint-cli2 again.

```bash
markdownlint-cli2 "**/*.md"
```

It seems to ingore the changes to the config. The output is the same.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
Summary: 1 error(s)
bad-doc.md:3 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Dupe"]
```

I change the config once more to add some invalid syntax.

```bash
cat > .markdownlint.yaml <<"EOF"
---
line_length: false

customRules:
  - "not-a-real-rule"

invalid_syntax
EOF
```

I run markdownlint-cli2 again.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Error: Unable to parse '/home/isme/tmp/tmp.2023-03-02.g1d5paLo/.markdownlint.yaml'; Parser 0: Unexpected number in JSON at position 1; Parser 1: Implicit map keys need to be followed by map values at line 7, column 1:


invalid_syntax
^^^^^^^^^^^^^^

    at /home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/node_modules/markdownlint/lib/markdownlint.js:1098:23

```

**Comment by iainelder** [comment]
It looks like the behavior depends on the file format of the configuration.

I repeated my repro using JSONC format instead of YAML format and got a different result.

I make a new empty directory.

```
cd "$(mktemp --dir)"
```

I create the same basic config as before in JSONC format.

```bash
cat > .markdownlint-cli2.jsonc <<"EOF"
{
    "line_length": false
}
EOF
```

I write a test file that should trigger the single-h1 rule.

```bash
cat > bad-doc.md <<"EOF"
# Heading

# Dupe
EOF
```

I run markdownlint-cli2.

```bash
markdownlint-cli2 "**/*.md"
```

As before, the tool accepts the configuration and detects a problem in the document.

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
Summary: 1 error(s)
bad-doc.md:3 MD025/single-title/single-h1 Multiple top-level headings in the same document [Context: "# Dupe"]
```

I change the config again to add a custom rule with a nonsense name.

```bash
cat > .markdownlint-cli2.jsonc <<"EOF"
{
    "line_length": false,
    "customRules": [
        "not-a-real-rule"
    ]
}
EOF
```

I run markdownlint-cli2 again. This time it fails: `Cannot find module 'not-a-real-rule'`. 

```text
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Error: Cannot find module 'not-a-real-rule'
Require stack:
- /home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js / Cannot find module '/tmp/tmp.FGeUfQVptT/not-a-real-rule' imported from /home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js
    at importOrRequireResolve (/home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:88:11)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async createDirInfos (/home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:582:3)
    at async main (/home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:863:5)
    at async /home/isme/.npm-packages/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:911:26
```

Going back to your comment:

> This sentence strongly suggests that your configuration file is not being used. Invalid YAML or a nonexistent custom rule should both cause the CLI to fail with an error message.

I have shown in both the YAML and JSONC cases that the configuration file is being used.

Invalid YAML does cause an error.

A nonexistent custom rule in YAML is ignored.

A nonexistent custom rule in JSON causes an error.

**Comment by iainelder** [comment]
For completeness, I show here that I can use the custom rule by configuring in JSONC format.

```
$ cat > .markdownlint-cli2.jsonc <<"EOF"
  {
      "line_length": false,
      "customRules": [
          "markdownlint-rule-github-internal-links"
      ],
      "config": {
          "github-internal-links": {
              "verbose": true
          }
      }
  }
  EOF
$ cat > bad-doc.md <<"EOF"
  # Heading
  
  [Bad link](/bad-link.md)
  EOF
$ markdownlint-cli2 "**/*.md"
markdownlint-cli2 v0.6.0 (markdownlint v0.27.0)
Finding: **/*.md
Linting: 1 file(s)
/tmp/tmp.FGeUfQVptT/bad-doc.md:1 github-internal-links #heading = Heading
Summary: 0 error(s)
```

(The fact that the github-internal-links didn't do what I expect doesn't matter. It turns out it checks only anchor links within a single document, not relative links to other documents in the repo.)

My initial problem is solved, and for that sake I would close this.

The different behavior for different formats, though, seems like a bug. Do you want to keep this open to track that?

**Comment by DavidAnson** [comment]
There are two kinds of configuration file that are supported: a simpler version that can only be used to configure built-in rules and a more feature-rich version that can be used to configure other things (like custom rules) as well. File names for the simpler version look like `.markdownlint.*` and for the more capable version `.markdownlint-cli2.*`. From what I see in the details you provided above, you only had problems when you tried to pass custom rules using the simpler format. If you use VS Code with the `markdownlint` extension, it includes schema validation for the JSON formats and should help alert you to problems like this. The documentation also reflects which file names support which features: <https://github.com/DavidAnson/markdownlint-cli2#configuration>. I'm glad you got this sorted out, I think we are good to close it!
