### ISSUE TITLE
Allow `package.json` as an alternative to separate config file

### ISSUE THREAD

**Issue by KillyMXI** [DavidAnson/markdownlint-cli2#14]
I'm looking for ways to use this package with least clutter.
I also want to have `.markdownlint.json` a separate file, for better tools integration. (For example, vscode extension supports only that file.)

Since I only need `.markdownlint-cli2.jsonc` for ignores, I would prefer to have it inside `package.json`, like many other tools allow.
This will also hopefully help to prevent the globs from getting overlooked when there is a time for them to be updated.

**Comment by DavidAnson** [comment]
Now that the VS Code extension supports `.markdownlint-cli2.jsonc`, are you still interested in this? So far you're the only person in 5 months to ask. :)

**Comment by KillyMXI** [comment]
This is cool.
I have to reevaluate now whether I can comfortably switch from CLI1 in my small projects.

Can use single config file now - check.
Have to explicitly maintain globs for markdownlint - I think I'm more relaxed about it now.

**Comment by DavidAnson** [comment]
Great! FYI, you can set `globs` and `ignores` both in the same `.markdownlint-cli2.jsonc` file if you want an empty command line.

https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2jsonc

**Comment by KillyMXI** [comment]
I migrated from `-cli` to `-cli2` in my packages and pretty happy about it, except some vscode extension [issue](https://github.com/DavidAnson/vscode-markdownlint/issues/169).

As a result, I have no need in this feature anymore. Feel free to close it or keep it for others consideration.

**Comment by DavidAnson** [comment]
Great! I'll close for now since it only came up once in 6 months.

**Comment by spyke113** [comment]
I also need this feature (config section inside `package.json`). How about [davidtheclark/cosmiconfig](https://github.com/davidtheclark/cosmiconfig)?

**Comment by Tatsh** [comment]
Yes why not reopen this? It was not actually implemented.
