### ISSUE TITLE
Adding "includes" as option

### ISSUE THREAD

**Issue by JPeer264** [DavidAnson/markdownlint-cli2#143]
## Current problem

Currently it is not possible to include folders/files which were already ignored in the config.
Assuming we have the following folder structure:

```
└── folder/
    ├── index.md
    ├── first.md
    ├── second.md
    └── subfolder/
        └── index.md
```

Where my config is as following as I want to exclude the `folder/`:

```json
{
  "ignores": ["folder/**/*"]
}
```

Now, when I want only to include `folder/index.md`, then there is no way of making that possible.

## Use case

This problem sounds like it could be solved by using the option `globs` alone and have normal globs by enabling and disabling files:

```json
{
  "globs": [
    "!./folder/**/*.md",
    "./folder/index.md"
  ]
}
```

But this doesn't quite work 100% perfectly together with [lint-staged](https://github.com/okonet/lint-staged) where only files are linted which are staged. With the glob from above, all files would be linted, even if they're not even added to the commit.

 We have many markdown files and folders where a couple of folders are ignored, except for one file inside the ignored folders. We're linting once all markdown files by command:

```sh
$ npx markdownlint-cli2 "**/*.md"
```

And once with `lint-staged` where only files have changed which were ready for commit. E.g.:

```sh
# this should not run `folder/index.md`
$ npx markdownlint-cli2 "folder/first.md" "folder/index.md"
```

## Proposal

By having `includes`, which enables single files/folders in an already ignored glob pattern.

Having the following config:

```json
{
  "ignores": ["folder/**/*.md"],
  "includes": ["folder/index.md"]
}
```

Then the following command, given the same folder structure as mentioned above, should run only lint `folder/index.md`:

```sh
$ npx markdownlint-cli2 "folder/**/*.md"
```

---

If that is something you would consider in this library, I could also go for the implementation.

**Comment by DavidAnson** [comment]
Two thoughts from my phone:

You can use the excluding "!" syntax with ignores also, so you should be able to use the approach you show with glob as an ignore instead. However, I think that will mean exclusions get linted even when they're not specified on the command line. But I think it's closer to what you want.

This is subtle, but I think if you create a new .markdownlint-cli2.jsonc in folder and configure the ignores (possibly including a "!" exclusion) there, then you'll get exactly the behavior you want without any new features.

**Comment by DavidAnson** [comment]
I'm not sure I understand the whole scenario above, but it seems to boil down to the following at the end of your post: 

> Then the following command, given the same folder structure as mentioned above, should run only lint `folder/index.md`:
> ```bash
> npx markdownlint-cli2 "folder/**/*.md"
> ```

If so, then adding the following two configuration files to your existing file structure accomplishes that goal with the current implementation:

```bash
user@HOST mdl-cli2-143 % cat folder/.markdownlint-cli2.jsonc 
{
  "ignores": [ "!(index.md)" ]
}
user@HOST mdl-cli2-143 % cat folder/subfolder/.markdownlint-cli2.jsonc 
{
  "ignores": [ "*" ]
}
user@HOST mdl-cli2-143 % ./node_modules/.bin/markdownlint-cli2 'folder/**/*.md' 
markdownlint-cli2 v0.7.0 (markdownlint v0.28.1)
Finding: folder/**/*.md
Linting: 4 file(s)
Summary: 1 error(s)
folder/index.md:1:9 MD047/single-trailing-newline Files should end with a single newline character
user@HOST mdl-cli2-143 % 
```

Every Markdown file in my example contains an error, so the presence of only `folder/index.md` above confirms the desired behavior.
