### ISSUE TITLE
not support `--ignore-path` ?

### ISSUE THREAD

**Issue by baixiaoyu2997** [DavidAnson/markdownlint-cli2#148]

**Comment by nschonni** [comment]
`#` is used to ignore a path as a separate glob https://github.com/DavidAnson/markdownlint-cli2#command-line

**Comment by DavidAnson** [comment]
Right. There is also an "ignores" property that may be useful. This CLI does not support any parameters, per say: https://dlaa.me/blog/post/markdownlintcli2
