### ISSUE TITLE
Pattern `**/*.md` does not includes paths like `source/_posts/foobar.md` while running the CLI via `npx`

### ISSUE THREAD

**Issue by rickygao** [DavidAnson/markdownlint-cli2#15]
I am working in a [`hexo`](https://hexo.io/) blog project, and I got

```
$ npx markdownlint-cli2 "**/*.md" "#node_modules"
markdownlint-cli2 v0.0.12 (markdownlint v0.22.0)
Finding: scaffolds/draft.md scaffolds/page.md scaffolds/post.md
Linting: 3 file(s)
Summary: 0 error(s)
```

which means `**/*.md` does not includes paths like `source/_posts/foobar.md`. However, it worked pretty well in the past few days. Is something going wrong?

**Comment by DavidAnson** [comment]
The "Finding" line shows that whatever tool/environment is running the command is expanding the glob instead of passing it to the CLI. Maybe try single quote or run the CLI directly if "npx" is responsible?

**Comment by rickygao** [comment]
> The "Finding" line shows that whatever tool/environment is running the command is expanding the glob instead of passing it to the CLI. Maybe try single quote or run the CLI directly if "npx" is responsible?

I tried single quote as well and got the same thing.

```
npx markdownlint-cli2 '**/*.md' '#node_modules'
markdownlint-cli2 v0.0.12 (markdownlint v0.22.0)
Finding: scaffolds/draft.md scaffolds/page.md scaffolds/post.md
Linting: 3 file(s)
Summary: 0 error(s)
```

And also I install `markdownlint-cli2` globally, then everything goes right. I wonder why it did worked in the past.

**Comment by rickygao** [comment]
I updated node and npm as well today, maybe this led a behavior change. I tried node@14, and `npx` runs well.

**Comment by DavidAnson** [comment]
Great!

**Comment by rickygao** [comment]
A couple of months passed, and I should note here that something has changed as far as I observed. npm 7.6.3 (or maybe some version behind) brings the previous behavior back, and a command like `npx markdownlint-cli2 "**/*.md" "#node_modules"` works now.
