### ISSUE TITLE
Separate file for ignore (and glob) config

### ISSUE THREAD

**Issue by NomarCub** [DavidAnson/markdownlint-cli2#156]
I want to reuse my rules for different repos, but copying `.markdownlint-cli2.jsonc` also copies globs and ignores specific to one repo. `.markdownlintignore` is not supported anymore.

**Comment by DavidAnson** [comment]
I don't think I want to split every option out into its own file. It's annoying enough when every tool wants to add a single file to the repo. But you could do what you want by making the main file `.markdownlint-cli2.cjs` and loading multiple files to create the unified configuration object.

Something like:
```
return {
  "config": {
    ...
  },
  "ignores": require("./myignores.json"),
  "globs": require("./myglobs.json")
};
```

**Comment by NomarCub** [comment]
Thanks! I might go with this then.
You can close this if you want. The config and precedence docs are not very clear to me. I might come back later and comment more here, when I have the time to think my migration situation through, if that's alright with you.
However, I think there's enough precedence out there for separate .ignore files. It could be made optional, so as not to clutter people's workspaces.
