### ISSUE TITLE
config: rename config key to rules

### ISSUE THREAD

**Issue by naseemkullah** [DavidAnson/markdownlint-cli2#17]
https://github.com/DavidAnson/markdownlint-cli2/blob/1a54e83c4d5d7aa12be051738e919b963ccaf5ec/markdownlint-cli2.js#L315-L316

It would be more comprehensive imho if this key were `rules` rather than `config`, since config implies all the various options in the config file, not just the configuration of rules. As such the `config` key should be deprecated  (and eventually removed) in favour of a `rules` key.

If it's too much hassle do no hesitate to close this issue.

**Comment by DavidAnson** [comment]
It's named `config` to be consistent with the library property it maps to: https://github.com/DavidAnson/markdownlint#optionsconfig

If I could rewind time, I'd probably do it more like what you propose, but I'm not sure I want to change this all now.

**Comment by naseemkullah** [comment]
ok np!
