### ISSUE TITLE
Add support for `.editorconfig` file

### ISSUE THREAD

**Issue by piranna** [DavidAnson/markdownlint-cli2#179]
I have seen other proposals to add support for `.editorconfig` as config file, but mine is more simple: instead of using it for full config, use it just only for the common fields that probably are already configured for other tools, so config gets more homogeneous. It would be just to detect if there's a `.editorconfig` file, and if so, use its values for the default values instead of `markdownlint-cli2` ones, and later process the regular `markdownlint-cli2` config files as usual.

**Comment by DavidAnson** [comment]
I’m not sure this proposal is consistent with the intent of EditorConfig: <https://editorconfig.org/>

They seem to want to fully specify the format and their “complete list of properties” does not include the ones you propose above: <https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties>

There is a process for proposing and approving new properties, but that’s not some thing I am looking to do at this time: <https://github.com/editorconfig/editorconfig/wiki/FAQ#how-to-propose-changes-to-the-format-including-new-properties-and-values>

There’s an alternate interpretation of this request where some of the supported properties (like insert_final_newline) could be re-interpreted in the context of markdownlint, but I worry that could get confusing and be a little too magical.

While I don’t always follow what ESLint does, in this case it seems they do not support what you propose either.

**Comment by nschonni** [comment]
I was going to say that ESLint had mostly delegated formatting rules to Prettier, but I think I am mixing that statement up with Stylelint v15. Prettier does respect the EditorConfig settings https://prettier.io/docs/en/configuration.html#editorconfig for what would be used here for Tabs, Indentation, Final Newline, and Line Length

**Comment by piranna** [comment]
> There’s an alternate interpretation of this request where some of the supported properties (like insert_final_newline) could be re-interpreted in the context of markdownlint

This is what I was proposing too.


> While I don’t always follow what ESLint does, in this case it seems they do not support what you propose either.

ESLint supports `.editorconfig` files with [eslint-plugin-editorconfig](https://github.com/phanect/eslint-plugin-editorconfig), and as @nschonni said, Prettier has built-in support for it and use editorconfig defined values by default if they are not defined at the `.prettierrc` file. That's exactly what I was asking for. In addition to that, `textlint` has a [rule](https://github.com/arrowrowe/textlint-rule-editorconfig) for editorconfig too.

**Comment by DavidAnson** [comment]
Here are the primary EditorConfig properties and how I think they map to markdownlint:

> **indent\_style**: set to “tab” or “space” to use hard tabs or soft tabs respectively.

Enables MD010/no-hard-tabs if set to “tab”, unenforceable if set to “space”.

> **indent\_size**: a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported). When set to “tab”, the value of **tab\_width** (if specified) will be used.
>
> **tab\_width**: a whole number defining the number of columns used to represent a tab character. This defaults to the value of **indent\_size** and doesn't usually need to be specified.

Both unenforceable unless they also force MD010 on and set spaces\\\_per\\\_tab.

> **end\_of\_line**: set to “lf”, “cr”, or “crlf” to control how line breaks are represented.

Meaningless.

> **charset**: set to “latin1”, “utf-8”, “utf-8-bom”, “utf-16be” or “utf-16le” to control the character set.

Meaningless.

> **trim\_trailing\_whitespace**: set to “true” to remove any whitespace characters preceding newline characters and “false” to ensure it doesn't.

Enables MD009/no-trailing-spaces with strict on if set to true, unenforceable if set to false. But if br\_spaces is set, the layout of the document may change; if it’s unset, then some spaces get ignored unexpectedly.

> **insert\_final\_newline**: set to “true” to ensure file ends with a newline when saving and “false” to ensure it doesn't.

Enables MD047/single-trailing-newline if set to true, unenforceable if set to false.

If my interpretation above is reasonable, none of these settings can be implemented more than halfway - and they come with confusing compromises. There’s also the question of how to merge settings in the event of conflict. And anyone who wants to configure other rules will need to create a configuration file for markdownlint anyway.

So I don’t see this being of much practical benefit?

**Comment by piranna** [comment]
Not like that, you need to think it the other way: not that a definition on `.editorconfig` enables a markdownlint rule, but instead markdownlint rules use editorconfig definitions if they are available, or its own internal default values if not. It's not about enforcing the values defined in the `.editorconfig` file, but use them as the default ones if user don't overwrite them in the rules configuration. For example:

- `MD005/list-indent` and `MD007/ul-indent`: `indent_size` and `tab_width` are used to define the default value of `spaces_per_tab` option if user doesn't overwrites it, if not rule default value of `1` is being used.
- `MD009/no-trailing-spaces`: if `br_spaces` or `list_item_empty_lines` parameters are enabled, that spaces are considered part of the markdown syntax, so when setting `trim_trailing_whitespace` they must be preserved and any extra one gets removed. The oposite occurs when `strict` is enabled and they are not needed, so they must be removed.
- `MD010/no-hard-tabs`: if `indent_style` is `tab`, rule does nothing because `editorconfig` says user wants tabs. Otherwise, `indent_size` and `tab_width` are used to define the default value of `spaces_per_tab` option if user doesn't overwrites it, if not rule default value of `1` is being used.
- `MD013/line-length`: `max_line_length` (not in the spec, but widely supported) definition can be used if available to define the value of `line_length`, otherwise use its default value of 80 columns.
- `MD047/single-trailing-newline`: if `insert_final_newline` is true, this rule works as usual, if it's false then the rule becomes a no-op.

So yes, I think usage of editorconfig can be easily integrated and very practical to do it, specially to make it easier to integrate markdownlint on other projects that already make use of editorconfig for other tools, so configuration doesn't get duplicated and/or conflicting :-)

> > **end_of_line**: set to “lf”, “cr”, or “crlf” to control how line breaks are represented.
> 
> Meaningless.
> 
> > **charset**: set to “latin1”, “utf-8”, “utf-8-bom”, “utf-16be” or “utf-16le” to control the character set.
> 
> Meaningless.

It's true there's no markdownlint rules for these ones, so they can be ignored. It's valid for editorconfig that some values are ignored if the editor interpreter (in this case, markdownlint) doesn't understand them. OTOH, rules for end of line and charset would be nice, but that's another discussion topic.

**Comment by DavidAnson** [comment]
I am aware of the principal of “don’t repeat yourself“, but this seems to set up a potentially confusing situation where someone configures markdownlint using one file and then a few days later ads or edits a completely different file which unexpectedly changes the way they’ve configured markdownlint, but only for some parameters and so they have to go back to the first file and maybe update it to get back in the behavior they had. I’m exaggerating a bit, yes, but the idea of splitting configuration does not really appeal to me.

This would also introduce the concept of different per-file-type configuration (.md handled differently than .markdown) which could add other kinds of confusion and would need to be merged with the existing per-directory behavior.

(And it’s another configuration file to recursively find all the way up the directory tree.)

**Comment by piranna** [comment]
> I’m exaggerating a bit

A little bit, yes. Configs at `.markdownlint-cli2.json` file would still get priority, so any change in `.editorconfig` would not affect, specially since defaults for markdownlint are pretty common, like the 80 columns, so any customization could have been already been done. Only case would be that they expected to use the 80 columns for markdown and later add an `.editorconfig` for their actual Javascript to 120 columns and markdown start to use 120 columns, but that's on their fault, both by not setting the specific columns for markdown files in the new `.editorconfig` file, or needing to set it now explicitly in the `.markdownlint-cli2` file, that would be very odd, since the purpose of the `.editoconfig` file is to define common values for everybody that downloads the repo (and the file).


> This would also introduce the concept of different per-file-type configuration (.md handled differently than .markdown) which could add other kinds of confusion and would need to be merged with the existing per-directory behavior.

I don't get you, why that would happen? Both `.md` and `.markdown` extensions would need to be configured anyway...


> (And it’s another configuration file to recursively find all the way up the directory tree.)

That's not an issue, https://www.npmjs.com/package/editorconfig already does the traverse and provides the final editorconfig configuracion to be used. I can agree that would be an extra dependency, though.

**Comment by DavidAnson** [comment]
> I don't get you, why that would happen? Both .md and .markdown extensions would need to be configured anyway...

The user may configure `[*.md]` and `[*.markdown]` differently in `.editorconfig` and invoke CLI2 with `*.md *.markdown`. Whereas linting configuration today is applied uniformly across all files which are being handled.

> That's not an issue, https://www.npmjs.com/package/editorconfig already does the traverse and provides the final editorconfig configuracion to be used.

Every directory may have its own `.editorconfig` file - that package would need to be invoked separately for each directory with files getting linted. Today, CLI2 finds and merges configuration files efficiently, but adding EditorConfig would introduce  an entirely separate mechanism/code path.

**Comment by piranna** [comment]
> The user may configure `[*.md]` and `[*.markdown]` differently in `.editorconfig`

Honestly, I can't be able to think of any sane reason to do it that doesn't involve being a misconfiguration done by error.


> adding EditorConfig would introduce an entirely separate mechanism/code path

The same as being currently done, it's just to add an extra line before reading/searching the `.markdownlint-cli2` files with something like `config = await editorconfig.parse(path)` and later do `Object.assign()`, there's no need for more.

**Comment by DavidAnson** [comment]
I appreciate your energy, but think you are minimizing a some of the legitimate concerns I’ve raised. For example, you said:

> MD047/single-trailing-newline: if insert_final_newline is true, this rule works as usual, if it's false then the rule becomes a no-op.

But as I quoted from the documentation (emphasis added):

> insert_final_newline: set to “true” to ensure file ends with a newline when saving and _“false” to ensure it doesn't_.

It’s not proper to ignore the false value with a no-op - users will expect _both_ configurations to do what they are supposed to. And implementing the false scenario is not otherwise in scope for markdownlint - nobody is asking for that.

I agree the basics of implementing EditorConfig integration are attainable, but worry doing so raises a variety of new problems to solve and/or behaviors to define, document, and test. The benefits seem small and the costs high.

There are already tools to implement EditorConfig support and I think they will provide a better experience - while any inconsistencies with markdownlint should be straightforward to identify and accommodate.

**Comment by piranna** [comment]
> It’s not proper to ignore the false value with a no-op - users will expect _both_ configurations to do what they are supposed to. And implementing the false scenario is not otherwise in scope for markdownlint - nobody is asking for that.

Yes, it's proper to ignore it, editorconfig spec allows explicitly that if a definition can't be understood by the software interpreting it (in this case, markdownlint), it's fine to ignore it. This allows to noop when `insert_final_newline` is false, but if you don't feel confortable with that, it also allows to totally ignore the `insert_final_newline` definition, and the same for any other definition that would force us to add new features of options to markdownlint.

**Comment by DavidAnson** [comment]
Because of the concerns I outline above, I do not intend to implement this behavior and will close the issue as "not planned". That said, anyone wanting such behavior could get it via a `.markdownlint.cjs` configuration file that looked for an `.editorconfig` file in the appropriate place, loaded and parsed it, then returned a collection of markdownlint rule settings to match.
