### ISSUE TITLE
Support hierarchical `.markdownlintignore` files

### ISSUE THREAD

**Issue by borekb** [DavidAnson/markdownlint-cli2#2]
This cli2 supports hierarchical config files (`.markdownlint.json`) but not ignore files (`.markdownlintignore`). This feels inconsistent, for example, I can customize lint rules per subfolder but can't customize ignore rules in the same way.

Why this is a problem in larger repos is described here: https://github.com/igorshubovych/markdownlint-cli/issues/45#issuecomment-667671464.

**Comment by DavidAnson** [comment]
This is currently by explicit design - there's more discussion in <https://github.com/DavidAnson/markdownlint-cli2/issues/2>. Specifically, all the globs need to be available before globbing starts for best performance. A single `.markdownlintignore` file in the current directory is easy to pre-read - but allowing multiple of them throughout the tree risks performance problems.

Aside: I may introduce "ignore" globs in `.markdownlint-cli2.json` for convenience, but those will explicitly be called out as a performance anti-pattern.

**Comment by borekb** [comment]
Thanks, the issue link should be #1 ([this comment](https://github.com/DavidAnson/markdownlint-cli2/issues/1#issuecomment-673867015) specifically) I believe.

**Comment by DavidAnson** [comment]
Yes, thanks for the correction! And there is an update there that's relevant here that may provide a nice resolution for both issues: ￼https://github.com/DavidAnson/markdownlint-cli2/issues/1#issuecomment-674140908
