### ISSUE TITLE
Not picking up .markdownlint.jsonc files in directory when using CLI

### ISSUE THREAD

**Issue by craigmac** [DavidAnson/markdownlint-cli2#21]
Is it possible to use this CLI tool and have it pickup the .markdownlint.jsonc file in current directory and/or it's parents up to a root?

I have a project with a bunch of them that works fine from VS Code, so I guess my other question might be: does the inheritance of these config files only work in conjunction with the VS Code Extension? If so, I think this could be made more clear, as it lock-in with a specific editor.

**Comment by DavidAnson** [comment]
The last two releases of the VS Code extension have used this CLI to implement linting. If you're seeing the behavior you want there, it can most likely be accomplished on the command line. Please describe the scenario you are trying to address, perhaps by pointing to a repository with the relevant file and directory structure.
