### ISSUE TITLE
validateMarkdownlintConfigSchema test failure after 2fe503d5

### ISSUE THREAD

**Issue by polyzen** [DavidAnson/markdownlint-cli2#215]
> Planned for 25 assertions, but got 24.

Reproducible with `npx ava test/markdownlint-cli2-test.js`

Works after you revert the commit, `npm install`, and re-run the tests.

**Comment by DavidAnson** [comment]
I'm not sure what you are reporting here. CI passes for that commit on 3 platforms crossed with 3 Node versions: https://github.com/DavidAnson/markdownlint-cli2/actions/runs/6210252508

Why are you trying to selectively run some of the tests with "npx" instead of via the "test" script or similar? It sounds like you are missing one of the test files for a scenario, possibly the new "showFound" directory.

**Comment by polyzen** [comment]
CI runs `test-cover`. The failure comes when running the `test` script, but can be isolated with the above command.

The whole repo is sourced.

**Comment by DavidAnson** [comment]
I'll give this a try. Are you doing some kind of test process where this matters?

**Comment by polyzen** [comment]
It's policy to run the test suite, if possible, as part of building packages for Arch Linux:
https://gitlab.archlinux.org/archlinux/packaging/packages/markdownlint-cli2/-/blob/main/PKGBUILD

**Comment by DavidAnson** [comment]
I may have figured this out while waiting for something. I should be able to try it on the computer shortly and if I'm right then I should have a fix pretty quickly.

**Comment by DavidAnson** [comment]
@polyzen, do you need a new release published to npm for this? Is fast-forwarding `main` branch to include this commit sufficient?

**Comment by polyzen** [comment]
Fast-forwarding is sufficient, thank you!

**Comment by DavidAnson** [comment]
Done. You can verify via `git log` that `main` branch contains exactly the public `v0.10.0` release plus only the test-only commit above. Thanks for pointing this out!

**Comment by DavidAnson** [comment]
@polyzen, super nitpick, the `pkgdesc` in the file you link to above appears to be from the `markdownlint-cli` package rather than this one. It's not wrong, but I never capitalize `markdownlint` like that. :)

**Comment by polyzen** [comment]
I had kept that from the package when it existed in the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=markdownlint-cli2#n6). Will update it.

**Comment by DavidAnson** [comment]
FYI, the follow-up commit I pushed to `main` a moment ago closes the race condition I thought of yesterday. Also test-only. I've never seen it happen. Up to you if you want to update to that.
