### ISSUE TITLE
Question: can customPlugin be installed globally?

### ISSUE THREAD

**Issue by zinizhu** [DavidAnson/markdownlint-cli2#224]
Background: I am working on a Markdown linting GitHub Action that is shared across many projects in the org, some of which are JS project managed with yarn/npm. To avoid messing up the project dependencies I tried to install the markdownlint-cli2 package along with the custom plugins globally, but then it gives me the error that the custom plugin package cannot be imported, for example:

```
Run DavidAnson/markdownlint-cli2-action@ed4dec634fd2ef689c7061d5647371d8248064f1
  with:
    globs: markdown-test/index.md
    config: .markdownlint-cli2.jsonc
    separator: ,
markdownlint-cli2 v0.10.0 (markdownlint v0.31.1)
Error: Failed due to error: AggregateError: Unable to require or import module 'markdownlint-rule-relative-links'.
```

Any idea why this happens? What's the correct way to configure it?

**Comment by zinizhu** [comment]
related issue https://github.com/theoludwig/markdownlint-rule-relative-links/issues/3

**Comment by DavidAnson** [comment]
If this is for GitHub, you may be interested in this Action that already exists: https://github.com/DavidAnson/markdownlint-cli2-action

Regarding global install of packages, CLI2 will try to `require` things via the standard Node.js mechanism (with the config directory prepended). If that finds the package you have identified, it should be loaded and used. This process can be tricky enough that you may need to debug your scenario specifically.

FYI that the next release of this tool will include a configuration option that lets you specify additional paths to scan. It is meant for scenarios like the VS Code extension where `require` does not scan global locations by default, but it may be useful in your scenario also.

**Comment by DavidAnson** [comment]
To answer your actual question, custom rules and output formatters CAN be installed globally and referenced by this tool. The second half of this workflow verifies that for output formatters: https://github.com/DavidAnson/markdownlint-cli2/blob/main/.github/workflows/ci.yml

**Comment by DavidAnson** [comment]
By the way, I misunderstood your first sentence and did not realize you were already using the action I linked to. Sorry!

**Comment by DavidAnson** [comment]
To debug this, you might temporarily create a workflow that does all of the steps manually and uses CLI2 as a package. Once you get that working, maybe try converting to the Action instead. But I think you will have an easier time experimenting if you use the command line tool to start. Good luck!

**Comment by zinizhu** [comment]
Thanks for the suggestions! Will give it a try and let you know.

**Comment by zinizhu** [comment]
> FYI that the next release of this tool will include a configuration option that lets you specify additional paths to scan. It is meant for scenarios like the VS Code extension where `require` does not scan global locations by default, but it may be useful in your scenario also.

Excited! Is there an estimate on when it will be launched?

**Comment by zinizhu** [comment]
Huh! Actually when using the markdownlint-cli2 CLI directly it is able to detect the globally installed custom plugin! Although I am not sure why it stopped to work when switching to use the corresponding GitHub Action.

**Comment by DavidAnson** [comment]
Good news! I hope that unblocks you for now. My guess is that GitHub runs Workflows/Actions in some kind of sandbox environment kind of similar to what VS Code does (Electron). They may block or limit access to global modules for safety and security reasons. If you can figure out what that location is, the upcoming ability to specify paths may permit you use the Action instead. As a guess, I would say new releases should go out in about a month.

**Comment by zinizhu** [comment]
Thank you David! I will close this issue as my problem is resolved now!
