### ISSUE TITLE
Absolute paths not processed

### ISSUE THREAD

**Issue by dylankerr-bis** [DavidAnson/markdownlint-cli2#23]
By analogy with https://github.com/igorshubovych/markdownlint-cli/pull/80, absolute paths do not appear to be processed. This prevents this CLI from being used with `lint-staged`, for example.

Actual behaviour:

```
PS C:\demo> .\node_modules\.bin\markdownlint-cli2 C:\demo\test.md
markdownlint-cli2 v0.1.3 (markdownlint v0.23.1)
Finding: C:\demo\test.md
Linting: 0 file(s)
Summary: 0 error(s)
```

Expected behaviour (demonstrated using a relative path):

```
PS C:\demo> .\node_modules\.bin\markdownlint-cli2 test.md
markdownlint-cli2 v0.1.3 (markdownlint v0.23.1)
Finding: test.md
Linting: 1 file(s)
Summary: 2 error(s)
test.md:1 MD041/first-line-heading/first-line-h1 First line in a file should be a top-level heading [Context: "No heading."]
test.md:3 MD036/no-emphasis-as-heading/no-emphasis-as-header Emphasis used instead of a heading [Context: "Wrong italics"]
```

As you can see from the backslashes, I am running Windows, which might be relevant if absolute paths have been confirmed to work on other operating systems.

**Comment by DavidAnson** [comment]
Per the documentation/[help text](https://github.com/DavidAnson/markdownlint-cli2#use), forward slash '/' is the recommended (maybe it should say "required") syntax. Please try with `C:/demo/test.md` instead.

I don't have any platform-specific code yet, but maybe the tool should pre-convert '\' to '/' on Windows to help with this?

**Comment by DavidAnson** [comment]
Additionally, `lint-staged` supports a `--relative` flag that may help?

**Comment by dylankerr-bis** [comment]
Thanks, David. I've confirmed that it behaves as expected with forward slashes in the absolute path, and tested your fix in the `next` branch - that now works with lint-staged.
The `--relative` flag wasn't appropriate in my case as I have other tools that didn't play nice with relative paths, so I appreciate you implementing the change here.
