### ISSUE TITLE
cannot print usage information if `globs` present in config

### ISSUE THREAD

**Issue by boneskull** [DavidAnson/markdownlint-cli2#249]
To reproduce:

1. Run `markdownlint-cli2`: invalid usage; help text prints)
2. Run `markdownlint-cli2 --help`: invalid usage; help text prints (note: I am not sure `--help` is recognized by the CLI at all)
3. Use the [example config](https://github.com/DavidAnson/markdownlint-cli2/blob/HEAD/test/markdownlint-cli2-yaml-example/.markdownlint-cli2.yaml)
4. Run `markdownlint-cli2` - linting occurs (expected)
5. Run `markdownlint-cli2 --help` - linting occurs (**not expected**)
6. Comment out `globs` in config and repeat steps 4 and 5; you should see help text both times

Suggested fix:

`--help` should short-circuit and _always_ print usage information

**Comment by DavidAnson** [comment]
--help is not a valid parameter: https://github.com/DavidAnson/markdownlint-cli2#command-line

**Comment by boneskull** [comment]
Yes, but it probably should be, otherwise there's no way to get help, right? 😄

**Comment by DavidAnson** [comment]
By the time you know enough to create the situation you describe above, you probably don't need that much help. :) That said, I don't object to adding something like this tonight or tomorrow.
