### ISSUE TITLE
Getting MD013 error on *.mdx files, but not *.md with MD013 rule disabled

### ISSUE THREAD

**Issue by dprothero** [DavidAnson/markdownlint-cli2#26]
I have disabled `MD013/line-length` in my `.markdownlint-cli2.js` configuration:

```js
module.exports = {
  config: {
    MD013: false,
    "no-inline-html": {
      // Add React components we want to allow here
      allowed_elements: ["IconExternalLink"],
    },
  },
  // The second "*.md" grabs markdown like README.md in the root
  globs: ["docs/**/*.{md,mdx,markdown}", "*.md"],
  ignores: ["node_modules"],
  customRules: [],
};
```

It works fine and ignores long lines in my `*.md` files, however, it reports errors for `*.mdx` files.

```
markdownlint-cli2 v0.2.0 (markdownlint v0.23.1)
Finding: docs/**/*.{md,mdx,markdown} *.md !node_modules
Linting: 24 file(s)
Summary: 1 error(s)
docs/writing/extras/markdown-features.mdx:205:81 MD013/line-length Line length [Expected: 80; Actual: 189]
```

**Comment by DavidAnson** [comment]
Please have a look at markdown-features.mdx or share a link. I'm guessing there is a comment directive in there that is disabling MD013. See: https://github.com/DavidAnson/markdownlint#configuration

Alternatively, could there be a configuration file in that directory that is overriding what you show here?

**Comment by dprothero** [comment]
Good call. I must not be understanding how `<!-- markdownlint-enable -->` works. Does it actually turn ALL rules back on?

[Here's the file](https://gist.github.com/dprothero/ad5255d51c1b6660392a837896b36bdd)

**Comment by dprothero** [comment]
OK, fencing the part of the doc I want markdownlint turned off with like this:

```
<!-- markdownlint-capture -->
<!-- markdownlint-disable -->

Don't lint this stuff

<!-- markdownlint-restore -->
```

And that's working great. Apologies for not fully RTFM.
