### ISSUE TITLE
Use of full JSONC Parser

### ISSUE THREAD

**Issue by Cielquan** [DavidAnson/markdownlint-cli2#267]
I use a JSONC file over JSON for my markdownlint-cli2 config to add comments.

In prettier via https://github.com/prettier/prettier/issues/15553 a new jsonc parser was added, which is released but I think only in the 4.0 alpha. With this new parser prettier adds trailing commas to jsonc source. When I ran my QA toolchain, after updating the tools, markdownlint suddenly was throwing. The reason was, that the jsonc config (with trailing commas) could not be correctly parsed. I looked up the stacktrace and found the [internal jsonc parser](
https://github.com/DavidAnson/markdownlint-cli2/blob/ffd0d58dfdec86dc00f143b91d456edb828b9e55/markdownlint-cli2.js#L39-L44), which is at base just `JSON.parse()` which in turn does not allow trailing commas hence the issue. Based on this https://github.com/prettier/prettier/issues/15553#issuecomment-1890458789 it would propably be a good to utilize a fully fledged jsonc parser like https://github.com/microsoft/node-jsonc-parser?

**Comment by theoludwig** [comment]
I have the same issue, after upgrading my dependencies (notably `prettier` to v3.2.1 and `markdownlint-cli2` to v0.12.0).
For now, the workaround is to downgrade Prettier to v3.1.1.

> a new jsonc parser was added, which is released but I think only in the 4.0 alpha.

The new JSONC parser was added to Prettier v3.2.0 already, [Changelog reference](https://prettier.io/blog/2024/01/12/3.2.0#new-jsonc-parser-added-15831httpsgithubcomprettierprettierpull15831-by-fiskerhttpsgithubcomfisker).

**Comment by DavidAnson** [comment]
This “hacky as hell and really terrible” approach has been in place since the beginning of the project in 2020 and hasn’t caused an issue in the four years since.

Until today when prettier opted everyone in.

Sorry for the inconvenience, I will look at addressing this soon.

https://github.com/DavidAnson/markdownlint-cli2/commit/db200dabd63403bdefe0c0856db7172f8cbe5a85

**Comment by theoludwig** [comment]
> Sorry for the inconvenience, I will look at addressing this soon.

No problem, and take your time! @DavidAnson  :heart:
Thank you for your work, markdownlint and related is a incredibly useful tool!

(even VSCode have issues with trailing comma in `.jsonc`: https://github.com/microsoft/vscode/issues/202422)

**Comment by mohamed2900** [comment]
> I use a JSONC file over JSON for my markdownlint-cli2 config to add comments.
> 
> In prettier via [prettier/prettier#15553](https://github.com/prettier/prettier/issues/15553) a new jsonc parser was added, which is released but I think only in the 4.0 alpha. With this new parser prettier adds trailing commas to jsonc source. When I ran my QA toolchain, after updating the tools, markdownlint suddenly was throwing. The reason was, that the jsonc config (with trailing commas) could not be correctly parsed. I looked up the stacktrace and found the [internal jsonc parser](https://github.com/DavidAnson/markdownlint-cli2/blob/ffd0d58dfdec86dc00f143b91d456edb828b9e55/markdownlint-cli2.js#L39-L44), which is at base just `JSON.parse()` which in turn does not allow trailing commas hence the issue. Based on this [prettier/prettier#15553 (comment)](https://github.com/prettier/prettier/issues/15553#issuecomment-1890458789) it would propably be a good to utilize a fully fledged jsonc parser like https://github.com/microsoft/node-jsonc-parser?
