### ISSUE TITLE
Publish this tool as a container image on dockerhub

### ISSUE THREAD

**Issue by vinman1** [DavidAnson/markdownlint-cli2#27]
As [this comment](https://github.com/DavidAnson/markdownlint-cli2/issues/16#issuecomment-759559924) suggests, it would be great to wrap this tool in a container image and publish it on dockerhub. It would make it even more accessible for:

- more general (non github) ci workflows
- local workflows

I would expect it to be called, as suggested in the linked comment, something like so:

```bash
$ docker run -v ${PWD}:/repo -w /repo DavidAnson/markdownlint-cli2:latest "**/*.md" "#node_modules"
```

The advantage of this project providing the container image is that releases of the image would then be synchronized with releases of this tool on `npmjs.org`, meaning a ci pipeline using the above command would always use the `latest` version of the tool for linting its markdown files.

**Comment by vinman1** [comment]
I'll try to start a PR soon with an example Dockerfile

**Comment by DavidAnson** [comment]
The latest Docker Desktop for Mac comes nearly ready to do this. I needed to `docker buildx create --use` and then everything worked. For probably valid reasons that are annoying, `buildx` seems to really only want to publish the image it builds, so I tweaked the scripts a little. Local development is now always for the single $VERSION tag - use `build-docker-image` and `test-docker-image` to iterate. When ready, `publish-docker-image` pushes $VERSION and latest to Docker Hub with support for both `amd64` and `arm64`. `test-docker-hub-image` verifies both are trivially functional using the local processor architecture.

The changes: https://github.com/DavidAnson/markdownlint-cli2/commit/dc44e13eff6368aacd0f0140abeee0898f0c264f

**Comment by vinman1** [comment]
Looks great! It was fun seeing this through with you 😉

**Comment by DavidAnson** [comment]
@vinman1, do you have a Twitter account? I will tweet about the new Docker support soon and can link to that if you have one. Otherwise I will link to your GitHub account.

**Comment by vinman1** [comment]
@DavidAnson , linking to my GitHub account will do just fine. thanks :smiley:
