### ISSUE TITLE
Why fixing deps version?

### ISSUE THREAD

**Issue by Mister-Hope** [DavidAnson/markdownlint-cli2#287]
Is there any reason this package choose to lock an exact version in every deps?

https://github.com/DavidAnson/markdownlint-cli2/blob/82c791e94c2e2ab2119437d61c722c8e0c20d6c9/package.json#L70

E.g.: yaml release 2.4, while I can only upgrade to it by force overriding the version.

**Comment by DavidAnson** [comment]
Explained here: https://github.com/DavidAnson/markdownlint-cli2/issues/154

**Comment by Mister-Hope** [comment]
I have to argue about this opinion.

What is said in the blog is fine, but it requires (said in blog):

> Automate some process to make sure you remain up-to-date.

Also the blog opinion is obviously too "aggressive". It's true that developers make release unworkable updates upstream, so that this affect any packages requiring it, but by requiring other packages, it means that you trust the package behavior (Obviously you haven't check every dependency and the whole dependency trees in you project). So, it's fair to say that your project can still have potential bugs and mysterious codes from upstream.

The correct behavior is actually trying to require any popular library which has capable developers, and try not require any deps that is no longer actively maintained (a lot of issues remain unhandled) or some unpopular ones. One of the basics (especially in node.js where you probably get 1k+ deps on just a medium size project), is to trust your deps chain, and believe even there are bugs long upstream, they will be fixed very soon.

---

Another thing is that it has almost no benefit to lock the version. The whole community is not doing the same thing. Even if you lock a dep A, its dependencies update may still break that version of dep A.

One of the biggest disadvantages is that locking to a version or refuse to update major version in time, will cause duplicate version of the package. The reason I opened this issue, is that I have a tool to track my deps number, and mark any dumplicate version of same deps with same major, them yaml are, when I install projects like eslint which also requires yaml, I will have the latest `2.4.1` in my project, yet I have to install an outdated deps `2.3.4` because of this package. It's exacerbating the "tons of deps" problem.

**Comment by Mister-Hope** [comment]
Repin: The original reply is updated

**Comment by DavidAnson** [comment]
I understand the points you make and agree the community does not pin.  However, it's my time that gets wasted when another project breaks their code in a patch release. And I've wasted that time on many occasions. I can't change everyone's behavior, but I can control my own and pinning is a safer practice. Correctness is more important to me than the chance of avoiding duplicated dependencies. Without pinning, users wind up running untested code and problems show up unexpectedly for them. With pinning, problems only show up during version updates and can be avoided by skipping the update. People who disagree with this approach and are willing to troubleshoot can choose to force version overrides via npm or yarn.

**Comment by DavidAnson** [comment]
I summarized my thinking in a blog post. I understand folks may disagree.

https://dlaa.me/blog/post/versionpinning
