### ISSUE TITLE
How can I see markdownlint-cli2 version?

### ISSUE THREAD

**Issue by misogihagi** [DavidAnson/markdownlint-cli2#289]
When I typed `npx markdownlint-cli2 --version`, outputs:
```
markdownlint-cli2 v0.12.1 (markdownlint v0.33.0)
Finding: --version !.git !node_modules
Linting: 0 file(s)
Summary: 0 error(s)
```

It looks to try to lint `--version` file.
How can I see markdownlint-cli2 version?

**Comment by DavidAnson** [comment]
You can run it with no parameters or you can use --help: https://github.com/DavidAnson/markdownlint-cli2?tab=readme-ov-file#command-line

**Comment by misogihagi** [comment]
I want a command to display only that version.
This would be useful when combined with the shell.

For example, typed in bash
```bash
 echo "this system uses node $(node -v)"
```
outputs `this system uses node v18.16.0`

**Comment by mondeja** [comment]
You can use this on linux:

```sh
$ alias getversion='markdownlint-cli2 | head -n 1 | cut -d" " -f2'
$ echo "this system uses markdownlint-cli2 $(getversion)"
this system uses markdownlint-cli2 v0.5.0
```
