### ISSUE TITLE
.markdownlint-cli2.jsonc ignored

### ISSUE THREAD

**Issue by siddharthvp** [DavidAnson/markdownlint-cli2#29]
Configurations specified via `.markdownlint-cli2.jsonc` file are being ignored. Only `.markdownlint-cli.jsonc` file is working.

**Comment by DavidAnson** [comment]
Example, please. The second file name you list isn't valid, so it's unlikely to be working.

**Comment by siddharthvp** [comment]
Whoops, my mistake - `.markdownlint2.jsonc` is the one that's not working, and `.markdownlint.jsonc` is the one that's working – all of which looks like the expected behaviour.
