### ISSUE TITLE
Default output format not matching markdownlint-cli

### ISSUE THREAD

**Issue by craigmac** [DavidAnson/markdownlint-cli2#33]
In https://github.com/DavidAnson/markdownlint-cli2/tree/main/formatter-default it says the default is to match markdownlint-cli and there is an example output, but that's not what I'm getting when I run the tool. I get output that begins like this:

```
markdownlint-cli2 v0.1.3 (markdownlint v0.23.1)
Finding: quick-start.md
Linting: 1 file(s)
Summary: 17 error(s)
```

So the first four lines are not markdownlint-cli compatible, unlike the example output on that page. This is an issue for me and I'm trying to resort to all kinds of brittle hacks to chop off those line using a custom function like this:

```sh
markdownlint2() {
  markdownlint-cli2 $1 | tail -n +5
}
```

But there's edge cases where this kind of thing is not working. I'd prefer that the default ouput formatter match the markdownlint-cli output.

**Comment by DavidAnson** [comment]
The banner is logged to `stdout` and errors are logged to `stderr`. By consuming only `stderr`, you should get the bare output you want.

**Comment by craigmac** [comment]
Perfect, thank you!
