### ISSUE TITLE
[Feature Request] Add ability to have a main configuration file name with `.cjs` extension

### ISSUE THREAD

**Issue by david-bojnansky** [DavidAnson/markdownlint-cli2#34]
Hello, could you please add ability to have a main configuration file name with `.cjs` extension? 

You have stated in README this:

```
Configuration via:
- .markdownlint-cli2.jsonc
- .markdownlint-cli2.yaml
- .markdownlint-cli2.js
- .markdownlint.jsonc or .markdownlint.json
- .markdownlint.yaml or .markdownlint.yml
- .markdownlint.js
```

and it could look like this:

```
Configuration via:
- .markdownlint-cli2.jsonc
- .markdownlint-cli2.yaml
- .markdownlint-cli2.js or .markdownlint-cli2.cjs
- .markdownlint.jsonc or .markdownlint.json
- .markdownlint.yaml or .markdownlint.yml
- .markdownlint.js or .markdownlint.cjs
```

It's important because of new `type` option in `package.json`.

Also as a bonus, it would be fine to add `.json` and `.yml` extensions too to `cli2`, at least `.json` because `.jsonc` is not such a standard yet.

**Comment by DavidAnson** [comment]
As you can see from the list of supported file names, I am trying to avoid including redundant file names with the CLI2 set of files. (Learning from my "mistake".) Having extra names is more confusing for users, adds complexity to the code, and creates more opportunity for mistakes. As I understand, CJS is used to refer to "Common JS" which is already a format that the JS type allows. As such, I am not inclined to make this change.

**Comment by david-bojnansky** [comment]
Yes, `type` can be set to `'commonjs'`, but when I set it to `'module'` then all `.js` files are considered as ESM. But `.cjs` will guarantees that file will be run as CommonJS regardless of module `type`. And if I am not wrong, then `.markdownlint.js` has to be of CommonJS type.

**Comment by DavidAnson** [comment]
I'm not sure the behavior of the `package.json` `type` field is significant here? If this configuration file exists, it is probably not used by the package as a script. Unless the presence of the file is interfering with something like ESLint?

I'm also not sure this file needs to be CommonJS? That may be true, but I need to try it. If it's possible to allow both kinds, I would be less inclined to make the extension explicit.

**Comment by DavidAnson** [comment]
Looks like you're right about this file needing to be CommonJS: https://nodejs.org/api/modules.html#the-mjs-extension

So my thinking at this point is that I may make a breaking change such that the extension for this file must be CJS.
