### ISSUE TITLE
Coloured text

### ISSUE THREAD

**Issue by monkey-knuckles** [DavidAnson/markdownlint-cli2#340]
Any possibility of adding separated headings for different files and highlighting different files with different colours.

Most linters have a --colour option.

Thanks

**Comment by DavidAnson** [comment]
You are describing formatter-pretty: https://www.npmjs.com/search?q=keywords:markdownlint-cli2-formatter

**Comment by monkey-knuckles** [comment]
That's fine I see the difference but when you have lots of markdown files it would nice to colour code them by file or something like that just to make the list easier to read.

Just a suggestion.

**Comment by DavidAnson** [comment]
Some of the formats here may be interesting: https://www.npmjs.com/package/markdownlint-cli2-formatter-summarize

**Comment by monkey-knuckles** [comment]
Thanks that looks like exactly what I wanted.
