### ISSUE TITLE
Vulnerability due to dependency on micromatch@4.0.5 

### ISSUE THREAD

**Issue by DanCRichards** [DavidAnson/markdownlint-cli2#355]
[There is a vulnerability in micromatch@4.0.5](https://github.com/micromatch/micromatch/blob/2c56a8604b68c1099e7bc0f807ce0865a339747a/index.js#L448). This is fixed with the version @4.0.6 with https://github.com/micromatch/micromatch/pull/247

More information about this vulnerability can be found https://github.com/micromatch/micromatch/issues/243

Ran tests. All passed.

I have created a pull request [here](https://github.com/DavidAnson/markdownlint-cli2/pull/354)

**Comment by DanCRichards** [comment]
I must commend your work on this open source project, it is greatly appreciated. I hope that this contribution can be seen as a thank you. 

Keep up the good work. 
Dan - Sydney, Australia.

**Comment by DavidAnson** [comment]
Dependabot already took care of this in `next` branch: https://github.com/DavidAnson/markdownlint-cli2/commit/5cce12f03d2af28031291c4d4cf0169fc043c711

**Comment by DanCRichards** [comment]
@DavidAnson  Can you please make a release of this then.

**Comment by DavidAnson** [comment]
The 4.0.7 / latest release of micromatch is a little weird: https://github.com/micromatch/micromatch/issues/259

Denial of service is not a security risk, so I would like to understand what's up with micromatch before publishing something that uses it and may regress functionality.

**Comment by dreamorosi** [comment]
Hi @DavidAnson, were you able to check the version? 

Micromatch released another version (4.0.8) that addresses https://github.com/advisories/GHSA-952p-6rrq-rcjv. 

Would it be possible to cut another release of markdownlint-cli2 that includes it? I see that the `next` branch already has it.

Alternatively, is it safe for us to override our package-lock and force 4.0.8? Is it compatible with `markdownlint-cli2`?

**Comment by DavidAnson** [comment]
I expect to release a new version very soon. That said, next branch passes all tests with the latest version of micromatch, so it should be fine for you to override locally in the meantime.
