### ISSUE TITLE
[QUESTION] How to configure a default config?

### ISSUE THREAD

**Issue by robsonpeixoto** [DavidAnson/markdownlint-cli2#364]
Thanks for this amazing project :heart: 

When I was using  https://github.com/DavidAnson/markdownlint I could create the `$HOME/.markdownlintrc` and configure some default options.

After reading the documentation, I didn't figure out how to create a default configuration. Is it possible? If so, how?

Thanks!

**Comment by DavidAnson** [comment]
markdownlint-cli supports a few configuration options (such as RC files) which this project (CLI2) does not. The various configuration options for this project are described in the README. You may be interested in the --config command-line option if you want to share a single configuration across many projects.
