### ISSUE TITLE
Possible to use relative paths for outputFormatters names?

### ISSUE THREAD

**Issue by FISHMANPET** [DavidAnson/markdownlint-cli2#38]
I'm working on using cli2 in a CI/CD Pipeline (specifically Azure DevOps Pipelines).  A tl;dr is that this would be slightly easier if the `name` for the formatter I'm using (junit specifically, but all of them that write a file seem to use the `name` value in the same way) would accept/understand an absolute path rather than always treat it as a relative path.  I'm not sure offhand how difficult it would be to implement that, so it's not a deal-breaker if it's not possible/too difficult/introduces too much complexity.

A longer explanation:
Azure DevOps (and many other CI CD tools) have system variables that represent the places where stuff goes.  This makes your pipeline more dynamic, and prevents you from relying on assumptions about file system layouts (layouts that could change at some point).  As an example, Azure DevOps checks out the repository to something like `/home/vsts/work/1/s`.  This is also the working directory that scripts execute from.  There is a separate directory for test directory, something like `/home/vsts/work/TestResults`, represented by the variable `Common.TestResultsDirectory`.  If I want to put my test results there, I have to specify a `name` value of something like `../TestResults/Test-$(Build.SourceVersion).xml`.  Then later on when I ingest the test results I can specify a path of `$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml`.  But this only works if the assumption continues to be true that `TestResults` is a folder that exists in the same directory as the working directory.  If I try to specify a name of `$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml` in my config file, the formatter treats it as "relative" rather than absolute.  The actual string value ends up being something like `/home/vsts/work/1/TestResults/Test-99aa992c60de7d7e44d77e7c4d84359174b61d65.xml` but the formatter looks in `/home/vsts/work/1/s/home/vsts/work/1/TestResults/Test-99aa992c60de7d7e44d77e7c4d84359174b61d65.xml`.

**Comment by FISHMANPET** [comment]
It might be as simple as using path.resolve() instead of path.join() and removing the reference to `directory` entirely here: https://github.com/DavidAnson/markdownlint-cli2/blob/79c5e552066e7ad28aca449e7f2eed692a603abf/formatter-junit/markdownlint-cli2-formatter-junit.js#L45
My guess is `directory` is being set to the present working directory somewhere else.  I know you've said in the past that directory is used for some "internal" stuff possibly related to the vscode integration, so I'm not sure what implication, if any, there would be in not using it in the formatters.

**Comment by DavidAnson** [comment]
I agree with your assessment that path.resolve is more appropriate. directory should probably remain to support relative paths. This applies to the JSON and JUnit formatters.

**Comment by FISHMANPET** [comment]
It looks like the behavior of resolve is that if multiple absolute paths are passed, the last one will be returned.  And if no absolute path is passed, it will construct it based on the current working directory.  I'm not sure in what situation `directory` would _not_ be the current working directory in a formatter, but whatever `directory`, if the `name` is an absolute path, path.resolve should figure it out.  I'll make a PR!

**Comment by DavidAnson** [comment]
The change should be quick, testing may need special handling because absolute paths can't be hard coded due to cross-platform CI. There should be precedent, either run the test from code OR use a JS config that determines the absolute path at runtime.

**Comment by DavidAnson** [comment]
Specifically, I'm thinking of another test directory like this: https://github.com/DavidAnson/markdownlint-cli2/tree/main/test/outputFormatters-params

Except use a JS file for config and populate the `name` parameter with something like `path.resolve(__dirname, "custom.xml")`. It may be necessary to further tweak that for Windows.

You'll use `npm run update-snapshots` to update the tests after adding an entry to the JS test file (don't forget to delete the output files as in the example I use).

**Comment by FISHMANPET** [comment]
I'm a little confused on how to actually implement a _failing_ test. Not being much of any knowledge of the specific testing tools in use here, I've been able to surmise that the snapshots are going to be snapshots of a passing test, and the actual tests are going to compare the test results against the snapshot (though it is possible to modify the test cases so the snapshots _fail_).  So I'm not sure how to get a snapshot of a successful test that my fail can be compared against.

I was able to user your suggestion and copied output-Formatters-params.  I created a test case like this in markdownlint-cli2-test-main.js
```  
testCase({
    "name": "outputFormatters-params-absolute",
    "args": [ "**/*.md" ],
    "cwd": directoryName("outputFormatters-params-absolute"),
    "pre": copyDirectory,
    "post": deleteDirectory,
    "usesRequire": true
  });
```
(I haven't pushed this up to GitHub yet, I can if you like).  I know from playing around that the execution is failing the way I expect it to.  For example, if I add a `stderrRe` to the test case I can confirm that the error is being written to stderr.  But it looks like that "failure" is being written into the snapshot and becomes the "expected" result that tests validate against.

**Comment by DavidAnson** [comment]
I've published new versions of both formatters with your change:
```text
+ markdownlint-cli2-formatter-json@0.0.6
+ markdownlint-cli2-formatter-junit@0.0.5
```

**Comment by FISHMANPET** [comment]
Sorry that I didn't have a chance to come back to this, but the tests I wrote look basically identical to what you ended up committing.

The workflow felt a little odd due to the "snapshot".  As far as I could tell the workflow to verify that a test fails is:
1) Make the change
2) Write a test that you believe tests the change, and take a "snapshot"
3) Remove the initial change
4) Run test, at this point it should fail

In the past where I've seen instances of test-driven-development you're able to immediately write a failing test before you write any code, but here it appears you need to actually implement your fix before you can make a test fail, because you need it to succeed before it can fail.

**Comment by DavidAnson** [comment]
The workflow is a little bit weird because of how snapshots behave. You can update them at any time, so it's not that you are locked into the initial behavior, but yes, I did something like what you describe where I reverted your change to make sure that the test and snapshot would have failed without it.
