### ISSUE TITLE
question: user-defined fix rules

### ISSUE THREAD

**Issue by xuan-cao-swi** [DavidAnson/markdownlint-cli2#381]
Is that possible to have user-defined fix rules to fix certain type of violation?
e.g. replace all MD040 error with console in code block
```json
{
    "fix": {
        "MD040": "console"
    }
}
```

**Comment by DavidAnson** [comment]
You could write a custom rule to add the "console" type to any unmarked code fence, but MD040 does not do that for you.

**Comment by xuan-cao-swi** [comment]
Thanks, I think I will need to read https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/CustomRules.md
