### ISSUE TITLE
`markdownlint-cli2` v0.4.0 fails when used as a pre-commit hook

### ISSUE THREAD

**Issue by lureza** [DavidAnson/markdownlint-cli2#41]
### Description

When launching the command 
```shell
pre-commit run -a
```
with `markdownlint-cli2` v0.4.0 as the single hook configured in the `.pre-commit-config.yaml` file, the following error occurs:
```shell
(venv) user:~/workspace/ (master)$ pre-commit run -a
markdownlint-cli2........................................................Failed
- hook id: markdownlint-cli2
- exit code: 2

markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Error: Not supported
    at getJsoncParse (/home/lrezakhanlou/.cache/pre-commit/repo85whfufa/node_env-system/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:38:5)
    at fs.promises.access.then (/home/lrezakhanlou/.cache/pre-commit/repo85whfufa/node_env-system/lib/node_modules/markdownlint-cli2/markdownlint-cli2.js:56:13)
```
The `venv` was created just before the `pre-commit` execution, and contains only this package with its dependencies, installed with `pip install pre-commit`.

I deleted the content in `/home/lrezakhanlou/.cache` and it resulted with the same error.

### Content of `.pre-commit-config.yaml` file

```yml
repos:
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.4.0
    hooks:
      - id: markdownlint-cli2
```

**Comment by DavidAnson** [comment]
It's failing on the "await" keyword which seems like maybe you are using an old/unsupported version of Node.js. Could you please check?

**Comment by lureza** [comment]
Thank you for the answer.
Here is the `nodejs` version installed on my system:
```shell
lrezakhanlou:~$ dpkg -s nodejs | grep Version
Version: 10.19.0~dfsg-3ubuntu1
```
I tried to do the upgrade, and apt says that it is already the latest version:
```shell
lrezakhanlou:~$ sudo apt upgrade nodejs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nodejs is already the newest version (10.19.0~dfsg-3ubuntu1).
...
```
My system is Ubuntu 20.04 LTS.

From [what I read](https://stackoverflow.com/questions/44545511/async-await-nodejs-support), `await` is supported from version 8.x, and since my system has 10.19.0 version, maybe it could be another cause?

**Comment by lureza** [comment]
Another information is that it does not fail with `markdownlint-cli2` v0.3.2

**Comment by lureza** [comment]
It indeed works with that version, thank you for your support.

However it requires to add an extra apt repository (https://github.com/nodesource/distributions/blob/master/README.md#deb) as the latest versions of `nodejs` are not available in the default ppa as shown above. I let you close the issue if you consider it acceptable that `markdownlint-cli2` v0.4.0 only works with Node 12 and later (possibly this information could be added in the README?)

In any case thank you again for the quick replies :smiley:
