### ISSUE TITLE
[FEAT] stdin support

### ISSUE THREAD

**Issue by xudyang1** [DavidAnson/markdownlint-cli2#414]
`markdownlint-cli` [supports read from stdin](https://github.com/igorshubovych/markdownlint-cli/issues/32), and `markdownlint` itself supports `--stdin` option to parse stdin input. Is it possible to make markdownlint-cli2 support stdin?

**Comment by DavidAnson** [comment]
I'll look into whether it is straightforward to do this by supporting `-` as with `cat` and `tar`. but if it is not, I will leave things as they are and recommend those other tools for this scenario.

FYI, I've asked before, and have not heard a particularly compelling scenario for why standard input was necessary versus creating and using a temporary file.

**Comment by xudyang1** [comment]
> I'll look into whether it is straightforward to do this by supporting `-` as with `cat` and `tar`. but if it is not, I will leave things as they are and recommend those other tools for this scenario.
> 
> FYI, I've asked before, and have not heard a particularly compelling scenario for why standard input was necessary versus creating and using a temporary file.

I would not say standard input is necessary for linting, but it does help editors like neovim to update diagnostics after changing the active buffer (without saving it to disk). Currently, `nvim-lint` uses `markdownlint` and `markdownlint-cli2` without stdin support, and because of that, users have to save the buffer to see diagnostics update. I am also trying to customize my configuration to make `markdownlint` in `nvim-lint` work from standard input, in that case, I would like to stick with `markdownlint` if it works well.

Anyway, thank you for developing an amazing linting/formatting tool for markdown!
