### ISSUE TITLE
Allowing --fix as option in markdownlint-cli2

### ISSUE THREAD

**Issue by JPeer264** [DavidAnson/markdownlint-cli2#43]
First off, nice cli thanks for that. I noticed that this cli has its own fix command `markdownlint-cli2-fix`, where only `fixDefault` is set to true and using the default run command. Many other linters such as `stylelint` or `eslint` are using the `--fix` option in order to fix the fixable errors.

The downside of having an own command is that we cannot reuse an already set up npm command such as `npm run lint -- --fix`.

I can also see from the codebase that no options are available, which means we could also allow an option for `markdownlint-cli2-config`: `--config [path]`. If you agree with options approach I could create a PR which are adding these.

related: #12

**Comment by DavidAnson** [comment]
This is deliberate. I explain more here: https://dlaa.me/blog/post/markdownlintcli2

**Comment by JPeer264** [comment]
Thanks a lot for the detailed post.
