### ISSUE TITLE
Add dotglob matching to Globby options

### ISSUE THREAD

**Issue by PanisSupraOmnia** [DavidAnson/markdownlint-cli2#44]
I would like it to either be one of the default options specified by the CLI, or else be configurable, to enable the `dot` option for Globby. This would let me use the standard "**/*.md" to also match files in a subdirectory that begins with a period (e.g. `.github/CONTRIBUTING.md`). Sorry if this is already an option and I just missed it!

**Comment by DavidAnson** [comment]
Directories and files beginning with a dot are conventionally hidden. I think the current behavior respects that and is appropriate as a default. Adding this as a configuration file option seems reasonable.

Link to relevant option in globby: https://github.com/mrmlnc/fast-glob#dot

**Comment by PanisSupraOmnia** [comment]
Thanks, that definitely makes sense!

**Comment by kachkaev** [comment]
Although `.` means `hidden` indeed, other linting tools I have used make no distinction between hidden and ‘normal’ files. This was my expectation for `markdownlint-cli` too and it took a while for me to discover the `--dot` option. It was quite puzzled by not seeing `.github/pull_request_template.md` amongst the linted files. I understand that this is a different project, just sharing (potentially relevant) user feedback.

**Comment by DavidAnson** [comment]
OK, thanks, maybe I will make it the default instead.
