### ISSUE TITLE
404 on npm registry

### ISSUE THREAD

**Issue by EricDriussi** [DavidAnson/markdownlint-cli2#467]
Hello! I'm getting a 404 when running the command `npm install markdownlint-cli2 --global` and also when going to the [npm page](https://www.npmjs.com/package/markdownlint-cli2) with the browser. npm per se seems fine so I thought I'd leave a notice here since the readme suggests using this method for installation but it seems broken ATM.

**Comment by EricDriussi** [comment]
Indeed, I am now getting 404s all over the place, thanks for the heads up!

**Comment by DavidAnson** [comment]
Thanks, @nschonni!
