### ISSUE TITLE
junit output formatter

### ISSUE THREAD

**Issue by davidwallis3101** [DavidAnson/markdownlint-cli2#47]
Hi,

Im running this in (well trying to) in a build pipeline and wanting a junit format..

the step I have is effectively:

```
find . -path "./node_modules" -prune -o -name "*.md" -print | xargs -L1 markdownlint-cli2-config .config/.markdownlint-cli2.jsonc
```

which works and I get the junit output but I need away of creating a file per md file or appending the existing xml output file - as I just end up with a file with the results of the last file processed..

**Comment by davidwallis3101** [comment]
Thanks - I was making use of someone else's example and then changing it for what I wanted where as I may have been better just starting from scratch :D 

I've ditched the find as recommended and now got this in my package.json:
```text
"markdownlint-cli2-config \".config/.markdownlint-cli2.jsonc\" \"**/*.md\" \"#node_modules\"" 
```
however in the junit output for say line length - it doesn't include  the file name - everything comes under markdownlint-cli-formatter-junit, so I think I'm going to need to call this on a per file basis :(

**Comment by DavidAnson** [comment]
testcase/classname should be the file name/relative path as shown in the documentation: https://www.npmjs.com/package/markdownlint-cli2-formatter-junit

I didn't choose the schema, but did try to match the output of another popular formatter for consistency (maybe ESLint).
