### ISSUE TITLE
cli2-config: Support sub directoires for inclusion of .markdownlint.yml

### ISSUE THREAD

**Issue by koppor** [DavidAnson/markdownlint-cli2#50]
I placed a custom cli2 configuration in sub directory `config`. Next to it, I placed a `.markdownlint.yml` file. According to https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2jsonc, cli2 should read that file:

> If a `.markdownlint.{jsonc,json,yaml,yml,js}` file (see below) is present in the same directory, it overrides the value of this property

This only works if `.markdownlint.yaml` is present in the current directory, not in the directory of the config file provided to `markdown-cli2-config`.

One can check this at the repository https://github.com/koppor/markdownlint-cli2-relative-customrule by executing following command (and removing the customRules statement in `config/.markdownlint-cli2.yaml`)

    markdownlint-cli2-config config/.markdownlint-cli2.yaml demo.md

Output:

    demo.md:3:1 MD033/no-inline-html Inline HTML [Element: kbd]

Relation: #49 is asking to support of custom rules relative to the configured file

**Comment by DavidAnson** [comment]
Closing because I do not understand the scenario.

**Comment by koppor** [comment]
> I understand the other issue you opened, but not this one. What are you trying to do here? You have a config file already, so why are you trying to create another one in the same location to override it?

I think, I mixed terms. I meant the file "configur[ing] rules for this part of the directory tree".

The layout is as follows:

![grafik](https://user-images.githubusercontent.com/1366654/175828380-335145ce-61a6-4e1c-bc50-f68c9a2b420c.png)

Based on the documentation, I would expect `markdownlint-cli2-config` to read `config/.markdownlint.yml` when called with `config/.markdownlint-cli2.yaml`. Currently, it does not.

Example:

```bash
$ npx markdownlint-cli2-config config/.markdownlint-cli2.yaml demo.md
markdownlint-cli2-config v0.4.0 (markdownlint v0.25.1)
Finding: demo.md
Linting: 1 file(s)
Summary: 1 error(s)
demo.md:3:1 MD033/no-inline-html Inline HTML [Element: kbd]
```

However, the file `config/.markdownlint.yml` reads as follows:

```yaml
default: true

# Inline HTML <https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033>
MD033: false
```

Thus, MD033 should not be reported as error. However, MD033 is reported as error.

**Comment by DavidAnson** [comment]
I understand the scenario, but feel implementing configuration file inheritance for `-config` is not necessary. It seems more clear for `-config` to specify a single configuration file which is parsed and applied. That configuration file can already specify all the options/configuration on its own. (In your scenario, the config in `yml` could be merged into the `yaml`.) If desired, configuration files can be put in the root directory to further customize things. I'll add a test to establish this last point, tweak the documentation, and close this issue because I feel the current behavior is appropriate.
