### ISSUE TITLE
Use arbitrary config file name with `-config`

### ISSUE THREAD

**Issue by jsumners** [DavidAnson/markdownlint-cli2#51]
I was attempting to do `markdownlint-cli2-config .confs/md-lint.yaml` and was getting the help output instead of linting. After navigating through the code path, I learned that the file name ***must*** end with `.markdownlint-cli2.yaml`. It would be nice if the tool inspected the file extension to determine the format and otherwise did not care about the filename.

**Comment by DavidAnson** [comment]
This should be addressed when I fix https://github.com/DavidAnson/markdownlint-cli2/pull/46
