### ISSUE TITLE
Support custom rule as ESM modules

### ISSUE THREAD

**Issue by Divlo** [DavidAnson/markdownlint-cli2#52]
Hello! :wave:

Thanks for maintaining `markdownlint`, this issue is a feature request to support custom rules using ESM modules.
Currently, all custom rules must be written with CommonJS.

Example, this is not working:
```js
import { filterTokens, addError } from 'markdownlint/helpers/helpers.js'

const rule = {
  names: ['no-dead-relative-links'],
  description: 'No dead relative links',
  tags: ['links'],
  function: (params, onError) => {
    // code of the rule
  }
}

export default rule
```

When executing `markdownlint-cli2` with `.markdownlint-cli2.jsonc`:
```jsonc
{
  "config": {
    "default": true,
    "no-dead-relative-links": true
  },
  "globs": ["**/*.{md,mdx}"],
  "ignores": ["**/node_modules"],
  "customRules": ["./tools/no-dead-relative-links.js"]
}
```

It throws:
```txt
markdownlint-cli2 v0.4.0 (markdownlint v0.25.1)
Finding: **/*.{md,mdx} !**/node_modules
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/divlo/Documents/workspace/tools/no-dead-relative-links.js from /home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js not supported.
Instead change the require of no-dead-relative-links.js in /home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js to a dynamic import() which is available in all CommonJS modules.
    at resolveAndRequire (/home/divlo/Documents/workspace/node_modules/markdownlint-cli2/resolve-and-require.js:16:10)
    at requireResolve (/home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:70:12)
    at /home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:77:36
    at Array.map (<anonymous>)
    at requireIds (/home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:77:24)
    at createDirInfos (/home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:497:11)
    at async main (/home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:784:5)
    at async /home/divlo/Documents/workspace/node_modules/markdownlint-cli2/markdownlint-cli2.js:832:26 {
  code: 'ERR_REQUIRE_ESM'
}
```

This should be easily fixable, but it could be a **BREAKING CHANGE**, depending on the Node.js version you support.
With the most recent Node.js version, you should be able to replace `require` with `await import` when you load custom rules.

**Comment by DavidAnson** [comment]
I will look into this! As you note, one challenge may be support from Node; presently the minimum version is 12 and I would want this feature to work consistently on all supported versions. Another possibly complicating factor is that calls to require are augmented with a call to resolve in order to support modules specified with a relative path. I'm not sure offhand if that is possible for ESM and that may block some scenarios people have asked for. Again, I would prefer that CJS and ESM rules behave identically.

**Comment by Divlo** [comment]
@DavidAnson Thanks for looking into this!
I see that there are several issues fixed in `next` and not yet released. The last release was 7 months ago, maybe it is worth to release a new version, maybe v0.5.0.
Do you have any plans for that?

**Comment by DavidAnson** [comment]
Yes, I am working on one more thing before releasing an update.
