### ISSUE TITLE
Feat: extend config from .markdownlint-cli2.jsonc instead of overwrite

### ISSUE THREAD

**Issue by MisterTimn** [DavidAnson/markdownlint-cli2#56]
First of all, thanks for this great tool! We are now using it to lint all our markdown and like the configurability and ease of use very much.

We are stumbling into a minor issue though with it, well not really an issue cause we can work around it but we think things could be cleaner

In the root of our project we do however need to have 2 markdownlint related config files, `.markdowlint-cli2.jsonc` and `.markdownlint-cli2.jsonc`. We also have some more specific configs in subdirectories which use `extends` to build upon the base config of the root.

Now we thought to integrate the root config into the `.markdownlint-cli2.json` file through the `config` key so we only have 1 config in the root (cleaner, less bulk) but then we can't extend from the config and we have to either
- use a base config in a .config folder or something similar and let all configs extend from that one
- revert to two config files

I think it would be nice to be able to set the tool to 'extend' from the `config` entry rather then replace! Makes for a very clean setup where you define a root `.markdownlint-cli2.jsonc` with your ignores, globs, base config, etc. and then you can rely on subdirectory configuration to build upon that.

Again this is very minor but just wanted to pitch the idea.

**Comment by DavidAnson** [comment]
Thanks! I'm not sure I understand what you are asking for here. `.markdownlint-cli2.jsonc` already merges `config` objects from parent to child directory: https://github.com/DavidAnson/markdownlint-cli2/blob/974dcd68e6e6f1b5dad1f457597ceae90674cdeb/merge-options.js#L19-L22

Or are you asking for `options.config` to support the `extends` property as used by `.markdownlint.jsonc`? If so, you could implement that today via `.markdownlint-cli2.cjs` by populating the `config` property with the file you want to extend.

Or is it something else? Can you show an example?

**Comment by MisterTimn** [comment]
> Or are you asking for `options.config` to support the `extends` property as used by `.markdownlint.jsonc`? If so, you could implement that today via `.markdownlint-cli2.cjs` by populating the `config` property with the file you want to extend.

yes the latter is our case and a colleague made the same remark with using a `.cjs` file! Will try out that.
