### ISSUE TITLE
Add Homebrew distribution

### ISSUE THREAD

**Issue by mvrahden** [DavidAnson/markdownlint-cli2#60]
Hi David,

it might be interesting to add the homebrew distribution channel of the binaries so people could easily install it via `brew install markdownlint-cli2` command.

Kind regards

**Comment by DavidAnson** [comment]
I'm not a Homebrew user/believer, so this is not particularly appealing to me.

See this issue for a discussion of the topic which seems very relevant here: https://github.com/igorshubovych/markdownlint-cli/issues/111

One thing that may be new is GitHub Actions to do the update: https://github.com/marketplace?type=actions&query=Homebrew+

**Comment by DavidAnson** [comment]
Note to anyone reading: I'm unlikely to make this change myself, but if someone wants to do so and implements it in a way that it's fully automated (perhaps via GitHub Action), I'm open to accepting their PR. The solution should be simple, reliable, and easy to understand - I don't want to have to become a Homebrew expert to fix this if it breaks. 😄

**Comment by adam-moss** [comment]
`markdownlint-cli2` is now available in `brew` via https://github.com/Homebrew/homebrew-core/commit/41a41a38044b7ad8bb0efa96bf01533c8433e3f6

I'll look at some further automation around this but I suspect the bump bot may pick it up automagically.
