### ISSUE TITLE
Update engines section in package.json

### ISSUE THREAD

**Issue by AlbertoSadoc** [DavidAnson/markdownlint-cli2#72]
Since [the updates done for v0.5.0](https://github.com/DavidAnson/markdownlint-cli2/commit/2a7312dde7ef6b9c1f590eb63d26dbccfed4f4b2#diff-6dc1f74cf48aa068d950faf273da52fd42e2c910c68fe267221d4782184517ea) using `require("node:path")` instead of `require("path")` the package.json needs an upgrade on the engines Node version. The package.json specifies engines Node >=14 and `require("node:path")` does not work with Node v14.17.2 at least

**Comment by AlbertoSadoc** [comment]
I understand your point and yes, we should be using the latest Node if only because of the vulnerabilities, but the version running on our build servers is out of the devs control, and v14 being still a LTS version it seems there isn't a big hurry to upgrade (I think the plan is to upgrade to v18 by spring next year).
So in the meantime we just need to be careful which packages we upgrade as some are dropping v14 already or specifying a higher minor (like `node-downloader-helper` which specifies in the engines `>=14.18`) which makes them incompatible with our build servers.
I raised this issue because by specifying `>=14` it says that v14.0.0 should be compatible but it is not due to the changes above.

**Comment by DavidAnson** [comment]
Note to self: The simplest correct condition appears to be `>=14.18.0`.
Source: https://nodejs.org/api/esm.html#node-imports
