### ISSUE TITLE
Enable recommended fix for `MD013/line-length - Line length`

### ISSUE THREAD

**Issue by havimaki-agilebits** [DavidAnson/markdownlint-cli2#97]
When running `markdownlint-cli2` against markdown files with a line-length longer than specified, this requires manual fixes.  If the `fix: true` could be set for `MD013/line-length - Line length`, it could just be a matter of counting characters and adding a line break.

**Comment by DavidAnson** [comment]
Duplicate with more info here: https://github.com/DavidAnson/markdownlint/issues/535
