### ISSUE TITLE
Include all formatters in Docker image

### ISSUE THREAD

**Issue by mschoettle** [DavidAnson/markdownlint-cli2#98]
Creating this to track the discussion that happened in #93 about only the default formatter being available in the published Docker image (link to last comment of that discussion: https://github.com/DavidAnson/markdownlint-cli2/pull/93#issuecomment-1321302005).

In a CI pipeline the current way to deal with this is to install the desired formatter before invoking `markdownlint-cli2` (this requires specifying a different entrypoint. See an example here: https://github.com/DavidAnson/markdownlint-cli2/tree/next/formatter-codequality#use-in-gitlab-ci

**Comment by DavidAnson** [comment]
@mschoettle You can (and please do!) now validate this using the container image tagged "next" in Docker Hub. That image happens to include your Code Quality formatter as well. :)
